### ISSUE TITLE
Failed at the react-native-iconic@0.0.2 postinstall script 'cd ./ios && pod install' on windows

### ISSUE THREAD

**Issue by hwnprsd** [prscX/react-native-iconic#2]

**Comment by prscX** [comment]
Thanks @d3fkon for raising the issue.

For iOS the library depends on [VBFPopFlatButton](https://github.com/victorBaro/VBFPopFlatButton), at time of npm install we have added this script to install the native dependency. 

I will check how we can put conditional scripts which runs only if system is MAC. 

Thanks
Pranav

**Comment by prscX** [comment]
Hi @d3fkon,

I have given a detailed thought and coming weekend I am planning to remove `postinstall` script from `package.json` in order to make it work across platforms (MAC, Windows, Linux). 

Meantime for quick fix you can fork this library and remove the script in order to proceed.

Thanks
Pranav

**Comment by prscX** [comment]
Hi @d3fkon,

I have done the needed changes and published V0.0.3. Can you please download and verify the same.

Please let me know in case you still face the same issue.

Thanks
Pranav
